spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:pong-clash
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        format_sql: true
    database-plataform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
